logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "lat rvx"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"
included-patches = "'add-splash-animation' 'materialyou'"
excluded-patches = "'Custom branding icon MMT' 'Custom branding icon Revancify Red' 'Custom branding icon Revancify Blue' 'custom-package-name' 'disable-hdr-video' 'microg-support' 'spoof-app-version' 'spoof-player-parameters' 'theme' translations' 'Custom branding name YouTube'"
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
excluded-patches = "'Custom branding icon MMT' 'Custom branding icon Revancify Red' 'Custom branding icon Revancify Blue' 'custom-package-name' 'microg-support' 'spoof-app-version' 'translations' 'Custom branding name YouTube Music'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"
