logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "lat rvx"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"
included-patches = "'Enable new splash animation' 'MaterialYou' 'MicroG support'"
excluded-patches = "'Custom branding icon YouTube' 'add-splash-animation' 'Custom package name' 'Enable debug logging' 'Disable HDR video' 'Spoof app version' 'Spoof player parameters' 'Theme' 'Translations' 'Custom branding name YouTube'"
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a
exclusive-patches = false                                             # excludes all patches by default
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
module-prop-name = "yt-rvx"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a
excluded-patches = "'Custom branding icon YouTube Music' 'Custom package name' 'Spoof app version' 'Translations' 'Custom branding name YouTube Music'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
module-prop-name = "ytm-rvx"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"
build-mode = "apk"
app-name = "Reddit"
